### ISSUE TITLE
Structurally interchangeable types

### ISSUE THREAD

**Issue by larsrbak** [larsrbak/dOvs_tests#13]
<h2>Stress tests:</h2>
<ul>
<li>var vector1 = {x: int, y: int } type vector2 = {x:int, y:int} <b>(untested)</b></li>
</ul>

<h2>Success tests</h2>
<ul>
<li>var vector1 = {x: int, y: int } type vector2 = vector1 <b>(untested)</b></li>
</ul>

**Comment by Gitnone** [comment]
I don't think I totally understand your tests. Please write if the linked test don't cover the cases otherwise close the issue.

* "eqOperWithRecordsUsingVars.tig" in c45f0b698f9313c82b8eb65de38a356f48fb4ab7
* "compBetweenTwoRecordsOfDifferentTypes.tig" in 24362510f9388f9ddd80bb73fb2a9f15f718a589
* eqOperWithRecords.tig" and "eqOperOrderOfFields.tig" in dd41b1732e9a750ec443f0d46a38702a0afbba0d
